In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/rul_feature_table.csv")

print(df.shape)
display(df.head())
display(df.info())
display(df.describe())

(76713, 31)

,reading_id,robot_id,timestamp,vibration_level,motor_temperature,torque_load,power_consumption,next_failure_time,RUL_hours,model_type,...,motor_temperature_rolling_std_24h,motor_temperature_change_rate,torque_load_rolling_mean_24h,torque_load_rolling_std_24h,torque_load_change_rate,power_consumption_rolling_mean_24h,power_consumption_rolling_std_24h,power_consumption_change_rate,stress_index,thermal_stress_index
0,READ-000001,ROB-0001,2023-01-07 00:00:00,0.288,70.1,136.1,1471.0,2024-07-11,13224.0,ARM-X7,...,0.000000,0.0,136.100000,0.000000,0.0,1471.000000,0.000000,0.0,200203.10,103117.10
1,READ-000002,ROB-0001,2023-01-07 06:00:00,0.135,70.2,139.5,811.1,2024-07-11,13218.0,ARM-X7,...,0.070711,0.1,137.800000,2.404163,3.4,1141.050000,466.619765,-659.9,113148.45,56939.22
2,READ-000003,ROB-0001,2023-01-07 12:00:00,0.277,47.9,123.5,752.5,2024-07-11,13212.0,ARM-X7,...,12.846141,-22.3,133.033333,8.429314,-16.0,1011.533333,398.987097,-58.6,92933.75,36044.75
3,READ-000004,ROB-0001,2023-01-07 18:00:00,0.172,58.2,111.2,610.9,2024-07-11,13206.0,ARM-X7,...,10.730952,10.3,127.575000,12.905135,-12.3,911.375000,382.431566,-141.6,67932.08,35554.38
4,READ-000005,ROB-0001,2023-01-08 00:00:00,0.465,52.8,68.2,1234.0,2024-07-11,13200.0,ARM-X7,...,9.588665,-5.4,110.600000,30.549086,-43.0,852.125000,268.095883,623.1,84158.80,65155.20

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76713 entries, 0 to 76712
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   reading_id                          76713 non-null  object
 1   robot_id                            76713 non-null  object
 2   timestamp                           76713 non-null  object
 3   vibration_level                     76713 non-null  float64
 4   motor_temperature                   76713 non-null  float64
 5   torque_load                         76713 non-null  float64
 6   power_consumption                   76713 non-null  float64
 7   next_failure_time                   76713 non-null  object
 8   RUL_hours                           76713 non-null  float64
 9   model_type                          76713 non-null  object
 10  installation_date                   76713 non-null  object
 11  factory_location                    76713 non-null  object
 12  operating_environment               76713 non-null  object
 13  time_since_last_maintenance_hours   76713 non-null  float64
 14  maintenance_count_to_date           76713 non-null  int64
 15  last_downtime_hours                 76713 non-null  float64
 16  last_maintenance_type               76713 non-null  object
 17  vibration_level_rolling_mean_24h    76713 non-null  float64
 18  vibration_level_rolling_std_24h     76713 non-null  float64
 19  vibration_level_change_rate         76713 non-null  float64
 20  motor_temperature_rolling_mean_24h  76713 non-null  float64
 21  motor_temperature_rolling_std_24h   76713 non-null  float64
 22  motor_temperature_change_rate       76713 non-null  float64
 23  torque_load_rolling_mean_24h        76713 non-null  float64
 24  torque_load_rolling_std_24h         76713 non-null  float64
 25  torque_load_change_rate             76713 non-null  float64
 26  power_consumption_rolling_mean_24h  76713 non-null  float64
 27  power_consumption_rolling_std_24h   76713 non-null  float64
 28  power_consumption_change_rate       76713 non-null  float64
 29  stress_index                        76713 non-null  float64
 30  thermal_stress_index                76713 non-null  float64
dtypes: float64(21), int64(1), object(9)
memory usage: 18.1+ MB

None

,vibration_level,motor_temperature,torque_load,power_consumption,RUL_hours,time_since_last_maintenance_hours,maintenance_count_to_date,last_downtime_hours,vibration_level_rolling_mean_24h,vibration_level_rolling_std_24h,...,motor_temperature_rolling_std_24h,motor_temperature_change_rate,torque_load_rolling_mean_24h,torque_load_rolling_std_24h,torque_load_change_rate,power_consumption_rolling_mean_24h,power_consumption_rolling_std_24h,power_consumption_change_rate,stress_index,thermal_stress_index
count,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,...,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000,76713.000000
mean,0.345415,57.098000,105.013096,1296.786174,5276.687810,1241.266811,2.820487,3.384664,0.345434,0.118056,...,8.415216,0.001722,105.009393,27.843690,0.002808,1296.812191,411.215779,-0.029913,136143.661321,74074.777266
std,0.127216,9.097938,29.635324,435.997879,3311.503294,1301.413673,1.883104,6.668081,0.066064,0.042829,...,2.947068,12.613379,15.056164,9.676148,41.672865,219.711417,141.631845,614.943484,61142.242912,27947.189097
min,0.050000,34.800000,38.600000,449.100000,6.000000,0.000000,0.000000,0.000000,0.092000,0.000000,...,0.000000,-36.100000,52.400000,0.000000,-116.800000,548.375000,0.000000,-1610.700000,23192.910000,18181.850000
25%,0.243000,49.500000,79.700000,919.900000,2424.000000,233.920603,1.000000,0.900000,0.300000,0.087309,...,6.308196,-9.000000,94.525000,20.873109,-29.800000,1144.425000,308.166096,-443.800000,88347.520000,51185.560000
50%,0.345000,57.100000,105.000000,1296.600000,4944.000000,827.193724,3.000000,2.100000,0.344750,0.118340,...,8.518216,0.000000,104.925000,28.207963,0.000000,1297.025000,418.520190,0.400000,125746.470000,72022.650000
75%,0.447000,64.600000,130.200000,1672.300000,7884.000000,1833.865038,4.000000,3.200000,0.390500,0.148298,...,10.564524,9.000000,115.375000,35.036647,29.800000,1448.725000,518.266244,440.800000,176431.440000,93953.100000
max,0.771000,89.800000,183.000000,2303.100000,13224.000000,7115.551762,7.000000,45.800000,0.616750,0.316784,...,19.091883,37.000000,163.025000,59.140370,114.200000,2100.700000,874.684913,1594.100000,377507.160000,193725.400000

In [2]:
df["RUL_hours"].describe()

count    76713.000000
mean      5276.687810
std       3311.503294
min          6.000000
25%       2424.000000
50%       4944.000000
75%       7884.000000
max      13224.000000
Name: RUL_hours, dtype: float64

Target feature

In [3]:
df.isna().sum().sort_values(ascending=False).head(20)

reading_id                           0
robot_id                             0
timestamp                            0
vibration_level                      0
motor_temperature                    0
torque_load                          0
power_consumption                    0
next_failure_time                    0
RUL_hours                            0
model_type                           0
installation_date                    0
factory_location                     0
operating_environment                0
time_since_last_maintenance_hours    0
maintenance_count_to_date            0
last_downtime_hours                  0
last_maintenance_type                0
vibration_level_rolling_mean_24h     0
vibration_level_rolling_std_24h      0
vibration_level_change_rate          0
dtype: int64

Checking no missing values in the dataset.

In [7]:
df["robot_id"].nunique(), df["robot_id"].value_counts().head()

(50,
 robot_id
 ROB-0001    2161
 ROB-0021    2153
 ROB-0050    2153
 ROB-0047    2121
 ROB-0022    2121
 Name: count, dtype: int64)

Cchecking for target feature.

In [8]:
df[["robot_id", "timestamp", "next_failure_time", "RUL_hours"]].head(20)

    robot_id            timestamp next_failure_time  RUL_hours
0   ROB-0001  2023-01-07 00:00:00        2024-07-11    13224.0
1   ROB-0001  2023-01-07 06:00:00        2024-07-11    13218.0
2   ROB-0001  2023-01-07 12:00:00        2024-07-11    13212.0
3   ROB-0001  2023-01-07 18:00:00        2024-07-11    13206.0
4   ROB-0001  2023-01-08 00:00:00        2024-07-11    13200.0
5   ROB-0001  2023-01-08 06:00:00        2024-07-11    13194.0
6   ROB-0001  2023-01-08 12:00:00        2024-07-11    13188.0
7   ROB-0001  2023-01-08 18:00:00        2024-07-11    13182.0
8   ROB-0001  2023-01-09 00:00:00        2024-07-11    13176.0
9   ROB-0001  2023-01-09 06:00:00        2024-07-11    13170.0
10  ROB-0001  2023-01-09 12:00:00        2024-07-11    13164.0
11  ROB-0001  2023-01-09 18:00:00        2024-07-11    13158.0
12  ROB-0001  2023-01-10 00:00:00        2024-07-11    13152.0
13  ROB-0001  2023-01-10 06:00:00        2024-07-11    13146.0
14  ROB-0001  2023-01-10 12:00:00        2024-07-11    13140.0
15  ROB-0001  2023-01-10 18:00:00        2024-07-11    13134.0
16  ROB-0001  2023-01-11 00:00:00        2024-07-11    13128.0
17  ROB-0001  2023-01-11 06:00:00        2024-07-11    13122.0
18  ROB-0001  2023-01-11 12:00:00        2024-07-11    13116.0
19  ROB-0001  2023-01-11 18:00:00        2024-07-11    13110.0

Checking target sanity.